### ISSUE TITLE
trio-stubs runtime error (mypy >= 1.4.0)

### ISSUE THREAD

**Issue by belm0** [python-trio/trio-typing#87] opened 2023-08-03 04:49 UTC
```
/.../lib/python3.8/site-packages/trio-stubs/__init__.pyi:129: error: INTERNAL ERROR -- Please try using mypy master on GitHub:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 1.4.1
Traceback (most recent call last):
  File "mypy/checker.py", line 582, in accept
  File "mypy/nodes.py", line 896, in accept
  File "mypy/checker.py", line 4721, in visit_decorator
  File "mypy/checkexpr.py", line 1291, in check_call
  File "mypy/checkexpr.py", line 1501, in check_callable_call
  File "mypy/checkexpr.py", line 1031, in apply_function_plugin
  File "/.../lib/python3.8/site-packages/trio_typing/plugin.py", line 496, in takes_callable_and_args_callback
    TypeVarType(
TypeError: __init__() missing required argument 'default' (pos 6)
```

**Comment by belm0** [comment] 2023-08-03 05:04
it seems to be fixed in trio-typing master-- need a release

**Comment by TeamSpen210** [comment] 2023-08-03 05:07
This is a duplicate of #84.

**Closed by TeamSpen210** 2023-08-03 05:07 UTC
